package cmd

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/noamsiegel/agents-toc/internal/config"
)

var (
	initForce bool
	initDir   string
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Scaffold a .agentsmdrc.yaml and ensure AGENTS.md has marker block.",
	Long: `init writes a default .agentsmdrc.yaml into the target directory and
prints a next-step hint. It will NOT overwrite an existing config unless
--force is passed. The AGENTS.md file itself is left to the first
` + "`agents-toc sync`" + ` call.`,
	RunE: func(cmd *cobra.Command, _ []string) error {
		dir := initDir
		if dir == "" {
			cwd, err := os.Getwd()
			if err != nil {
				return err
			}
			dir = cwd
		}
		abs, err := filepath.Abs(dir)
		if err != nil {
			return err
		}
		path := filepath.Join(abs, config.DefaultConfigName)
		if _, err := os.Stat(path); err == nil && !initForce {
			return fmt.Errorf("%s already exists (use --force to overwrite)", path)
		} else if err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		if err := os.MkdirAll(abs, 0o755); err != nil {
			return err
		}
		def := config.Default()
		data, err := def.Marshal()
		if err != nil {
			return err
		}
		header := "# .agentsmdrc.yaml — generated by `agents-toc init`.\n" +
			"# See https://github.com/noamsiegel/agents-toc/blob/main/docs/CONFIG.md\n"
		if err := os.WriteFile(path, append([]byte(header), data...), 0o644); err != nil {
			return err
		}
		out := cmd.OutOrStdout()
		fmt.Fprintf(out, "wrote %s\n", path)
		fmt.Fprintln(out, "next: `agents-toc sync` to populate AGENTS.md")
		return nil
	},
}

func init() {
	initCmd.Flags().BoolVar(&initForce, "force", false, "overwrite an existing .agentsmdrc.yaml")
	initCmd.Flags().StringVar(&initDir, "dir", "", "directory to scaffold into (default: current directory)")
	rootCmd.AddCommand(initCmd)
}
