// Package render turns scanned entries into the markdown body that lives
// between the AGENTS.md fenced markers.
package render

import (
	"fmt"
	"strings"

	"github.com/noamsiegel/agents-toc/internal/config"
	"github.com/noamsiegel/agents-toc/internal/scan"
)

// Render returns the rendered block body. Caller appends it between the
// configured markers; this function does NOT emit the markers themselves.
//
// The output is deterministic: entries are pre-sorted by the caller, group
// order matches Config.Sources, and the per-line template runs through a
// stable string replacement.
func Render(entries []scan.Entry, cfg *config.Config) string {
	if len(entries) == 0 {
		return cfg.Render.EmptyMessage
	}
	if cfg.Render.GroupBy == "none" {
		return renderFlat(entries, cfg)
	}
	return renderGrouped(entries, cfg)
}

// renderFlat ignores label grouping and emits one line per entry.
func renderFlat(entries []scan.Entry, cfg *config.Config) string {
	var b strings.Builder
	for i, e := range entries {
		if i > 0 {
			b.WriteByte('\n')
		}
		b.WriteString(formatLine(cfg.Render.LineTemplate, e))
	}
	return b.String()
}

// renderGrouped buckets entries by label in the order labels first appear in
// Config.Sources, then renders each bucket with the group template.
func renderGrouped(entries []scan.Entry, cfg *config.Config) string {
	// Preserve source-defined order; entries within a group keep their
	// scanner-provided order (already sorted by the caller).
	labelOrder := make([]string, 0, len(cfg.Sources))
	seen := map[string]bool{}
	for _, src := range cfg.Sources {
		if !seen[src.Label] {
			labelOrder = append(labelOrder, src.Label)
			seen[src.Label] = true
		}
	}
	buckets := map[string][]scan.Entry{}
	for _, e := range entries {
		buckets[e.Label] = append(buckets[e.Label], e)
	}
	var groups []string
	for _, label := range labelOrder {
		bucket := buckets[label]
		if len(bucket) == 0 {
			continue
		}
		var lines strings.Builder
		for i, e := range bucket {
			if i > 0 {
				lines.WriteByte('\n')
			}
			lines.WriteString(formatLine(cfg.Render.LineTemplate, e))
		}
		groups = append(groups, formatGroup(cfg.Render.GroupTemplate, label, lines.String(), len(bucket)))
	}
	return strings.Join(groups, "\n")
}

// formatLine substitutes {path}, {name}, {summary}, {label} placeholders.
func formatLine(template string, e scan.Entry) string {
	r := strings.NewReplacer(
		"{path}", e.Path,
		"{name}", e.Name,
		"{summary}", e.Summary,
		"{label}", e.Label,
	)
	return r.Replace(template)
}

// formatGroup substitutes {label}, {lines}, {count} placeholders.
func formatGroup(template, label, lines string, count int) string {
	r := strings.NewReplacer(
		"{label}", label,
		"{lines}", lines,
		"{count}", fmt.Sprintf("%d", count),
	)
	return r.Replace(template)
}

// Block returns the full block content with the configured markers wrapped
// around the rendered body, plus the standard generated-by header comment.
func Block(entries []scan.Entry, cfg *config.Config, version string) string {
	body := Render(entries, cfg)
	header := fmt.Sprintf("<!-- Generated by agents-toc %s. Do not hand-edit. Run `agents-toc sync` to refresh. -->", version)
	var b strings.Builder
	b.WriteString(cfg.Target.MarkerStart)
	b.WriteByte('\n')
	b.WriteString(header)
	b.WriteString("\n\n")
	b.WriteString(body)
	b.WriteByte('\n')
	b.WriteByte('\n')
	b.WriteString(cfg.Target.MarkerEnd)
	return b.String()
}
